### ISSUE TITLE
Systemd service doesn't get removed after uninstall 

### ISSUE THREAD

**Issue by nasedase** [kmicki/SteamDeckGyroDSU#29]
Ran the uninstaller, systemd service is still active and I can't find it anywhere. Running disable command shows no service available.

`Oct 24 02:35:34 systemd[1520]: Started Steam Deck Gyro DSU Server.
Oct 24 02:35:34 systemd[29452]: sdgyrodsu.service: Failed to locate executable /home/$USER/sdgyrodsu/sdgyrodsu: No such file or directory
Oct 24 02:35:34 systemd[29452]: sdgyrodsu.service: Failed at step EXEC spawning /home/$USER/sdgyrodsu/sdgyrodsu: No such file or directory
Oct 24 02:35:34 systemd[1520]: sdgyrodsu.service: Main process exited, code=exited, status=203/EXEC
Oct 24 02:35:34 systemd[1520]: sdgyrodsu.service: Failed with result 'exit-code'.
Oct 24 02:35:35 systemd[1520]: sdgyrodsu.service: Scheduled restart job, restart counter is at 12247.
Oct 24 02:35:35 systemd[1520]: Stopped Steam Deck Gyro DSU Server.`

`systemctl disable sdgyrodsu.service
Failed to disable unit: Unit file sdgyrodsu.service does not exist.`

**Comment by kmicki** [comment]
It's a user service so you have to add `--user` option to every `systemctl` command. And the command have to be run by the same user that installed the service.

Following are the first or lines of the uninstall script:

    echo "Uninstalling the service"
    systemctl --user -q stop sdgyrodsu.service >/dev/null 2>&1
    systemctl --user -q disable sdgyrodsu.service >/dev/null 2>&1
    rm $HOME/.config/systemd/user/sdgyrodsu.service >/dev/null 2>&1

The uninstall script has to be run by the same user that run the installer (`deck` usually), otherwise it won't work.
